services:
    sonata.admin.service:
        class: Wdr\InowebBundle\Admin\ServiceAdmin
        arguments: [~, Wdr\InowebBundle\Entity\Service, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Контент", label: "Сервисы"}

    wdr_inoweb.admin.image:
        class: Wdr\InowebBundle\Admin\FileAdmin
        arguments: [~, Wdr\InowebBundle\Entity\File, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Контент", label: "Изображения"}

    wdr_inoweb.admin.user:
        class: Wdr\InowebBundle\Admin\UserAdmin
        arguments: [~, Wdr\InowebBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Контент", label: "Пользователи"}
