services:
    sonata.admin.service:
        class: Wdr\InowebBundle\Admin\ServiceAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Контент"
              label: "Сервис"
        arguments:
            - ~
            - Wdr\InowebBundle\Entity\Service
            - ~
        roles:
            - ROLE_ADMIN
